language: go

go:
  - "1.10"

install:
  #Installs Go Meta Linter (Golint and Go vet are also supported independently)
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - $GOPATH/bin/gometalinter.v2 --install
  - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip 
  - unzip sonar-scanner-cli-4.2.0.1873-linux.zip 
  - rm sonar-scanner-cli-4.2.0.1873-linux.zip 
  - mv sonar-scanner-4.2.0.1873-linux sonar-scanner 

script:
  # Execute Go Meta Linter
  - $GOPATH/bin/gometalinter.v2 samples/ > gometalinter-report.out || true
  # And then execute SonarCloud analysis which will run its own code analysis, and also reuse the linters' results
  - sonar-scanner/bin/sonar-scanner -Dsonar.projectKey=githubAndroidProject -Dsonar.host.url=http://sonarqube.acoba.com -Dsonar.login=bd648c5067f7d3fd5e0508f59f2f6969f3f30f07 -Dsonar.projectKey=githubAndroidProject -Dsonar.java.binaries=.

cache:
  directories:
  - '$HOME/.sonar/cache'
